"""
    Use code generated by ogrinspect command to initialize GIS data.
    See http://geodjango.org/docs/layermapping.html for more information.
"""
from optparse import make_option

from django.core.management.base import NoArgsCommand, CommandError
from django.contrib.gis.utils import LayerMapping, add_postgis_srs
from django.core import management

from core import models

class Command(NoArgsCommand):
    help=''
    option_list= NoArgsCommand.option_list + ()

    def get_version(self):
        return "0.1"

    def handle_noargs(self, **options):
        
        # These use unusual Spatial Reference System
        # NAD 1983 StatePlane Illinois East FIPS 1201 Feet
        # http://spatialreference.org/ref/esri/102671/
        # This needs to be done before syncdb
#        add_postgis_srs(102671)
        
        management.call_command('syncdb')

        lm = LayerMapping(models.CommunityArea, 'data/maps/community_areas/Community_area.shp', models.communityarea_mapping)
        lm.save(verbose=True)
        print "Community Areas initialized."
        models.CommunityArea.objects.filter(area_number='0').delete()
        print "Bogus Community Areas cleared"
        print
        
        lm = LayerMapping(models.Station, 'data/maps/cta_stations/DATA_ADMIN_CTASTATION.shp', models.station_mapping)
        lm.save(verbose=True)
        print "CTA Stations initialized."
        print
